openapi: 3.0.0
info:
  version: 1.0.0
  title: Penguin Tracker API
  description: An API to manage penguin satellite tracking data and admin users
servers:
  - url: https://penguintrackerapi.fly.dev
    description: 'Live Server'
paths:
  /admin/createadmin:
    post:
      summary: Create a new admin
      description: Endpoint to create a new admin. Only accessible to Superadmins.
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminData'
      responses:
        '201':
          description: Admin created successfully
  /admin/getadmin:
    get:
      summary: Get admin information
      security:
      - BearerAuth: []
      responses:
        '200':
          description: A list of admins
  /admin/softdeleteadmin/{id}:
    delete:
      summary: Soft delete an admin
      security:
      - BearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
      responses:
        '200':
          description: Admin soft deleted successfully
  /admin/updateadminpassword:
    put:
      summary: Update admin password
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Admin password updated successfully
  /admin/login:
    post:
      summary: Log in as an admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in successfully
  /admin/penguins:
    get:
      summary: Get all penguin data
      responses:
        '200':
          description: A list of penguin data
  /admin/penguins/addpenguin:
    post:
      summary: Add new penguin data
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PenguinData'
      responses:
        '201':
          description: Penguin data added successfully
  /admin/penguins/edit:
    put:
      summary: Update penguin data
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                lastPosition:
                  type: array
                  items:
                    type: number
      responses:
        '200':
          description: Penguin data updated successfully
  /admin/postPerformanceData:
    post:
      summary: Post performance data
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformanceData'
      responses:
        '201':
          description: Performance data posted successfully
  /admin/getperformancedata:
    get:
      summary: Get performance data
      responses:
        '200':
          description: Performance data
  /admin/putperformancedata:
    put:
      summary: Update performance data
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformanceData'
      responses:
        '200':
          description: Performance data updated successfully
  /admin/patchperformancedata:
    patch:
      summary: Patch performance data
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformanceData'
      responses:
        '200':
          description: Performance data patched successfully
components:
  schemas:
    AdminData:
      type: object
      required:
        - username
        - employeeId
        - password
        - role
      properties:
        username:
          type: string
          minLength: 1
        employeeId:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 8
        role:
          type: string
          enum: ["superadmin", "developer"]
    PenguinData:
      type: object
      required:
        - penguinName
        - lastPosition
        - lastUpdate
        - speciesName
        - ageAtTagging
        - taggedPosition
        - taggedTime
        - taggedBy
      properties:
        penguinName:
          type: string
          minLength: 1
        lastPosition:
          type: array
          items:
            type: number
        lastUpdate:
          type: string
          format: date-time
        speciesName:
          type: string
        ageAtTagging:
          type: string
        taggedPosition:
          type: string
        taggedTime:
          type: string
          format: date-time
        taggedBy:
          type: string
    PerformanceData:
      type: object
      required:
        - totalPenguinTracked
        - lastUpdated
      properties:
        totalPenguinTracked:
          type: number
        lastUpdated:
          type: string
          format: date-time
  securitySchemes:
    BearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT   

